### ISSUE TITLE
String.format doesn't work

### ISSUE THREAD

**Issue by jhartman** [scalagwt/scalagwt-scala#13]
Here's the output from ant gwtc when trying to use Scala's String.format. I'm guessing an implicit isn't being inserted?

```
 [java] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
 [java]     at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:109)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:276)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
 [java]     at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:116)
 [java]     at com.google.gwt.dev.jjs.ast.JReturnStatement.traverse(JReturnStatement.java:39)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor$ListContextImmutable.traverse(JModVisitor.java:170)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemoveImmutable(JModVisitor.java:336)
 [java]     at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:83)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
 [java]     at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:137)
 [java]     at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:133)
 [java]     at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:82)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
 [java]     at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:426)
 [java]     at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:395)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
 [java]     at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:890)
 [java]     at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:615)
 [java]     at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:545)
 [java]     at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:33)
 [java]     at com.google.gwt.dev.Precompile.precompile(Precompile.java:278)
 [java]     at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
 [java]     at com.google.gwt.dev.Precompile.precompile(Precompile.java:141)
 [java]     at com.google.gwt.dev.Compiler.run(Compiler.java:232)
 [java]     at com.google.gwt.dev.Compiler.run(Compiler.java:198)
 [java]     at com.google.gwt.dev.Compiler$1.run(Compiler.java:170)
 [java]     at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:88)
 [java]     at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:82)
 [java]     at com.google.gwt.dev.Compiler.main(Compiler.java:177)
 [java] Caused by: java.lang.NoSuchMethodError: java.lang.String.format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
 [java]     at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1086)
 [java]     at com.google.gwt.dev.jjs.impl.UnifyAst.access$800(UnifyAst.java:120)
 [java]     at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.visit(UnifyAst.java:333)
 [java]     at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:240)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
 [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
 [java]     ... 32 more
 [java]       [ERROR] at Unknown(0): String.format($this.toString(), (Object[]) ((TraversableOnce) args.map(new StringLike$$anonfun$format$1($this), Seq$.MODULE$.canBuildFrom())).toArray(Manifest$.MODULE$.Object()))
 [java]          com.google.gwt.dev.jjs.ast.JMethodCall
 [java]       [ERROR] at Unknown(0): return String.format($this.toString(), (Object[]) ((TraversableOnce) args.map(new StringLike$$anonfun$format$1($this), Seq$.MODULE$.canBuildFrom())).toArray(Manifest$.MODULE$.Object()))
 [java]          com.google.gwt.dev.jjs.ast.JReturnStatement
 [java]       [ERROR] at Unknown(0): {
 [java]   return String.format($this.toString(), (Object[]) ((TraversableOnce) args.map(new StringLike$$anonfun$format$1($this), Seq$.MODULE$.canBuildFrom())).toArray(Manifest$.MODULE$.Object()));
 [java] }
 [java]          com.google.gwt.dev.jjs.ast.JBlock
 [java]       [ERROR] at Unknown(0): {
 [java]   return String.format($this.toString(), (Object[]) ((TraversableOnce) args.map(new StringLike$$anonfun$format$1($this), Seq$.MODULE$.canBuildFrom())).toArray(Manifest$.MODULE$.Object()));
 [java] }
 [java]          com.google.gwt.dev.jjs.ast.JMethodBody
 [java]       [ERROR] at Unknown(0): public static String format(StringLike $this, Seq args);
 [java] 
 [java]          com.google.gwt.dev.jjs.ast.JMethod
 [java] Shutting down PersistentUnitCache thread
```

**Comment by gkossakowski** [comment]
AFAIR, GWT doesn't support `String.format` method. Am I wrong?

**Comment by stephenh** [comment]
Right, this happens because the jribble code is compiled against the user's server-side classpath (which has JDK6), so String.format resolves and makes it into the jribble file, but the GWT ASTs for the String type are super sourced/emulated and end up not having the resolved method implemented. So UnifyAst blows up.

In a pure-Java GWT codebase, this would be reported as a compile error by the embedded ecj compiler.

For this one specific issue, we could attempt to add an emulated String.format method to GWT's String implementation, but it won't solve the general issue of this happening any time emulated types (either from GWT proper or in the user's own GWT code) drift from their canonical API.

**Comment by jhartman** [comment]
Interesting. I should have known GWT didn't support it in the first place. I just used + instead.
